<a href="https://colab.research.google.com/github/manower35/Python_Basic_Level/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is a library in Python used for working with arrays. It also has functions for working with domains like linear algebra, fourier transform, and matrices.

In [1]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Print the array
print(my_array)

[1 2 3 4 5]


NumPy arrays are more efficient for numerical operations compared to standard Python lists.

In [2]:
# Perform a simple operation (add 5 to each element)
new_array = my_array + 5

# Print the new array
print(new_array)

[ 6  7  8  9 10]


NumPy is a cornerstone in AI and machine learning due to its efficiency in handling large datasets and performing mathematical operations. Here are some key ways it's used:

*   **Data Representation:** NumPy arrays are the standard way to represent data in most ML libraries. Datasets, images, and other forms of data are often stored as NumPy arrays.

*   **Mathematical Operations:** Many ML algorithms involve extensive mathematical operations like matrix multiplication, vector addition, and element-wise calculations. NumPy provides highly optimized functions for these operations.

*   **Integration with Libraries:** Libraries like scikit-learn, TensorFlow, and PyTorch are built on top of or integrate seamlessly with NumPy, allowing you to use NumPy arrays directly in your models.

*   **Data Preprocessing:** NumPy is used for tasks like scaling, normalization, and reshaping data before feeding it into an ML model.

*   **Model Implementation:** You can use NumPy to implement ML algorithms from scratch, which can be helpful for understanding how they work.

Here's a simple example demonstrating matrix multiplication, a common operation in ML:

In [3]:
import numpy as np

# Create two NumPy matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result_matrix = np.dot(matrix_a, matrix_b)

# Print the result
print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResult of matrix multiplication:")
print(result_matrix)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of matrix multiplication:
[[19 22]
 [43 50]]


NumPy and machine learning:

*   **Scalar:** A single value.
*   **Matrix:** A 2D dimensional array
*   **Tensor:** A multi-dimensional array. A 1D array is a vector, a 2D array is a matrix, and arrays with more dimensions are generally referred to as tensors.

Here are examples using NumPy:

In [7]:
import numpy as np

# Scalar (0-dimensional array)
scalar = np.array(10)
print("Scalar:")
print(scalar)
print("Dimension:", scalar.ndim)
print("Shape:", scalar.shape)

Scalar:
10
Dimension: 0
Shape: ()


In [5]:
# Vector (1-dimensional array)
vector = np.array([1, 2, 3, 4])
print("\nVector:")
print(vector)
print("Dimension:", vector.ndim)
print("Shape:", vector.shape)



Vector:
[1 2 3 4]
Dimension: 1
Shape: (4,)


In [6]:
# Matrix (2-dimensional array)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:")
print(matrix)
print("Dimension:", matrix.ndim)
print("Shape:", matrix.shape)


Matrix:
[[1 2 3]
 [4 5 6]]
Dimension: 2
Shape: (2, 3)


In [8]:
# 3D Tensor
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Tensor:")
print(tensor_3d)
print("Dimension:", tensor_3d.ndim)
print("Shape:", tensor_3d.shape)


3D Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3
Shape: (2, 2, 2)


In [12]:
import numpy as np

# Generate a single random float between 0 and 2
random_float = np.random.rand()
print("Single random float:", random_float)

Single random float: 0.5824522023667327


In [13]:
# Generate an array of random floats
random_float_array = np.random.rand(3, 2) # 3 rows, 2 columns
print(random_float_array)

# Generate a single random integer within a range (e.g., between 1 and 10)
random_int = np.random.randint(1, 11) # upper limit is exclusive
print("\nSingle random integer (1-10):", random_int)

[[0.17180298 0.98427183]
 [0.7084051  0.12340544]
 [0.01886002 0.5666362 ]]

Single random integer (1-10): 1


In [15]:
# Generate an array of random integers
# 4 random integers between 10 and 100
random_int_array = np.random.randint(10, 101, size=(4,))
print("\nArray of random integers (10-100):")
print(random_int_array)


Array of random integers (10-100):
[52 87 34 99]


In [16]:
# Generate random numbers from a normal distribution (mean=0, std dev=1)
random_normal = np.random.randn(2, 2)
print("\nRandom numbers from normal distribution:")
print(random_normal)
print("\nArray of random floats:")


Random numbers from normal distribution:
[[-1.90552678 -0.61290971]
 [ 0.71258637 -0.57314964]]

Array of random floats:
