<a href="https://colab.research.google.com/github/manower35/Python_Basic_Level/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://docs.pytorch.org/docs/stable/index.html

PyTorch is an open-source machine learning framework that helps you build and train neural networks. It's known for its flexibility and ease of use, making it a popular choice for both researchers and developers.

In [5]:
import torch

# Create a tensor (a multi-dimensional array, similar to a NumPy array)
x = torch.rand(2, 3)
# Print the results
print("Original tensor (x):")
print(x)

Original tensor (x):
tensor([[0.4479, 0.6701, 0.0892],
        [0.2104, 0.0446, 0.6867]])


In this example:

1.  We import the `torch` library.
2.  We create a 2x3 tensor `x` filled with random numbers using `torch.rand()`.
3.  We perform matrix multiplication of `x` with its transpose (`x.T`) using `torch.matmul()` and store the result in `y`.
4.  Finally, we print both the original tensor and the result.

In [2]:
import torch

# Scalar (0D tensor)
scalar_tensor = torch.tensor(5)
print("Scalar tensor:", scalar_tensor)
print("Dimensions:", scalar_tensor.ndim)

Scalar tensor: tensor(5)
Dimensions: 0


In PyTorch, data is primarily represented as **tensors**. Tensors are multi-dimensional arrays, similar to NumPy arrays, but with the added capability of running on GPUs for faster computation.

Here's how scalars, vectors, matrices, and higher-dimensional arrays relate to tensors:

*   **Scalar:** A single number. In PyTorch, a scalar is a tensor with zero dimensions (a 0D tensor).
*   **Vector:** A one-dimensional array of numbers. In PyTorch, a vector is a 1D tensor.
*   **Matrix:** A two-dimensional array of numbers. In PyTorch, a matrix is a 2D tensor.
*   **Tensor:** The general term for an array with one or more dimensions. A 3D tensor could represent a cube of numbers, and higher dimensions are possible

In [3]:
# Vector (1D tensor)
vector_tensor = torch.tensor([1, 2, 3])
print("\nVector tensor:", vector_tensor)
print("Dimensions:", vector_tensor.ndim)

# Matrix (2D tensor)
matrix_tensor = torch.tensor([[1, 2], [3, 4]])
print("\nMatrix tensor:")
print(matrix_tensor)
print("Dimensions:", matrix_tensor.ndim)



Vector tensor: tensor([1, 2, 3])
Dimensions: 1

Matrix tensor:
tensor([[1, 2],
        [3, 4]])
Dimensions: 2

3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimensions: 3


In [4]:
# 3D Tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D tensor:")
print(tensor_3d)
print("Dimensions:", tensor_3d.ndim)


3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimensions: 3


In [6]:
# Perform a simple operation (matrix multiplication)
y = torch.matmul(x, x.T)

print("\nResult after matrix multiplication (y):")
print(y)


Result after matrix multiplication (y):
tensor([[0.6576, 0.1853],
        [0.1853, 0.5178]])
