<a href="https://colab.research.google.com/github/manower35/Python_Basic_Level/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TensorFlow** is an open-source library used for building and training machine learning models. It uses "tensors", which are like multi-dimensional arrays, to perform calculations.

In [3]:
import tensorflow as tf

# Scalar (0-dimensional tensor)
scalar = tf.constant(10, dtype=tf.int32)
print("Scalar:", scalar)

Scalar: tf.Tensor(10, shape=(), dtype=int32)


In [4]:
# Vector (1-dimensional tensor)
vector = tf.constant([1, 2, 3, 4], dtype=tf.float32)
print("Vector:", vector)

Vector: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
# Matrix (2-dimensional tensor)
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
# Tensor (n-dimensional tensor - in this case, a 3D tensor)
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=tf.float32)
print("Tensor:", tensor)
print("Tensor dtype:", tensor.dtype)

# Perform a simple operation (matrix multiplication)
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(tensor_a, tensor_b)

# Print the result of the matrix multiplication
print("Matrix multiplication result:", result)
print("Matrix multiplication result dtype:", result.dtype)

Tensor: tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
Tensor dtype: <dtype: 'float32'>
Matrix multiplication result: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Matrix multiplication result dtype: <dtype: 'int32'>
